version: "3"
services:
  redis:
    image: redis:3.2
    deploy:
     placement:
        constraints: [node.labels.zone == internal]
     labels:
      - "com.df.notify=true"
      - "com.df.distribute=true"
      - "com.df.port=6379"
      - "com.df.srcPort=6379"
      - "com.df.reqMode=tcp"
    networks:
      - redis
      - proxy_proxy
networks:
  proxy_proxy:
    external: true
  redis:
     driver: overlay