version: "3"
services:
  jenkins:
    image: jenkinsci/jenkins
    deploy:
     placement:
        constraints: [node.labels.zone == internal]
     labels:
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_traefik-net"
    networks:
      - jenkins
      - traefik_traefik-net
    volumes:
      - jenkins_home:/var/jenkins_home
networks:
  traefik_traefik-net:
    external: true
  jenkins:
     driver: overlay
volumes:
  jenkins_home:
   driver: convoy